# Generated by Django 5.0.14 on 2025-08-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
